import type { EnemyProfile } from './engine'

// Five office archetypes, each a fighting-style remix of the same stickman
// (recolored, not re-drawn) rather than distinct sprite art. All five stay
// in a warm red/orange/yellow "villain" family so the whole swarm reads as
// one mob at a glance — the player's cool blue is what actually stands out.
export const ENEMY_ROSTER: EnemyProfile[] = [
  {
    id: 'micromanager',
    name: 'THE MICROMANAGER',
    tint: 'rgba(204, 70, 24, 0.55)',
    healthMult: 0.85,
    dmgMult: 0.9,
    speedMult: 0.95,
    aggression: 0.5,
    dashBias: 0.18,
    airBias: 0.35,
    blockBias: 0.55,
    chainBias: 0.7,
    thinkMin: 100,
    thinkMax: 170,
  },
  {
    id: 'reply_all',
    name: 'REPLY-ALL',
    tint: 'rgba(214, 150, 20, 0.55)',
    healthMult: 0.6,
    dmgMult: 0.65,
    speedMult: 1.1,
    aggression: 0.85,
    dashBias: 0.12,
    airBias: 0.2,
    blockBias: 0.12,
    chainBias: 0.97,
    thinkMin: 55,
    thinkMax: 95,
  },
  {
    id: 'marathoner',
    name: 'THE MARATHONER',
    tint: 'rgba(224, 96, 24, 0.55)',
    healthMult: 0.9,
    dmgMult: 0.85,
    speedMult: 1.4,
    aggression: 0.45,
    dashBias: 0.6,
    airBias: 0.15,
    blockBias: 0.2,
    chainBias: 0.55,
    thinkMin: 80,
    thinkMax: 130,
  },
  {
    id: 'influencer',
    name: 'THE INFLUENCER',
    tint: 'rgba(224, 46, 40, 0.55)',
    healthMult: 0.7,
    dmgMult: 0.95,
    speedMult: 1.05,
    aggression: 0.55,
    dashBias: 0.2,
    airBias: 0.75,
    blockBias: 0.25,
    chainBias: 0.7,
    thinkMin: 80,
    thinkMax: 130,
  },
  {
    id: 'hero',
    name: 'THE HERO OF THEIR OWN STORY',
    tint: 'rgba(190, 30, 30, 0.6)',
    healthMult: 1.1,
    dmgMult: 1.05,
    speedMult: 1.1,
    aggression: 0.62,
    dashBias: 0.32,
    airBias: 0.4,
    blockBias: 0.3,
    chainBias: 0.95,
    thinkMin: 70,
    thinkMax: 110,
  },
]
